# Generated by Django 2.2.7 on 2019-11-05 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0002_remove_fridge_ingredients'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['fridge', 'product', '-amount']},
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fridge',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='fridge.Fridge'),
            preserve_default=False,
        ),
    ]
