# Generated by Django 2.2.7 on 2019-11-05 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0003_auto_20191105_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='fridge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fridge.Fridge'),
        ),
    ]
