# Generated by Django 2.2.7 on 2019-11-05 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0004_auto_20191105_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
    ]
