# Generated by Django 2.2.7 on 2019-11-05 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0006_requirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='fridge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fridge.Fridge'),
        ),
    ]
