# Generated by Django 2.2.7 on 2019-11-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0008_ingredient_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=78, unique=True),
        ),
    ]
