# Generated by Django 2.2.7 on 2019-11-04 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corretora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vencimento', models.DateField()),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('precoAtualizado', models.DateField(blank=True, null=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tesdir.Tipo')),
            ],
            options={
                'ordering': ['tipo', 'vencimento'],
            },
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('sinal', models.IntegerField(default=1)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=6)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rendimento', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('anotacoes', models.CharField(blank=True, max_length=100)),
                ('corretora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tesdir.Corretora')),
                ('titulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tesdir.Titulo')),
            ],
            options={
                'verbose_name_plural': 'Transações',
                'ordering': ['-data', 'corretora', 'titulo'],
            },
        ),
    ]
