# Generated by Django 2.2.7 on 2020-03-10 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesdir', '0002_auto_20200310_1220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transacao',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Transações'},
        ),
    ]
